# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - task: SonarCloudPrepare@2
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'lucas-paulger-sonarsource'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'lucas-paulger-sonarsource_react-demo'
      cliProjectName: 'react-demo'
      cliSources: '.'
  - task: SonarCloudAnalyze@2
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'

  - task: SonarCloudPublish@2
    inputs:
      pollingTimeoutSec: '300'

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"
